import React from 'react';
//import ReactDOM from 'react-dom';
import App from './App';

import '@testing-library/jest-dom/extend-expect';
import * as rtl from '@testing-library/react';

afterEach(rtl.cleanup);


// Started with testing render
describe('it renders App to allow testing components', () => {
  it('it mounts a simulated DOM', () => {
    const simulatedDOM = rtl.render(<App/>);
    const container = document.body;

    console.log('simulatedDOM is ', simulatedDOM);
    console.log('container is ', container);  
    //console.log('simulatedDOM with debug is ', simulatedDOM.debug());

  })

  it('verifies Kitt text exists', () => {
    const wrapper = rtl.render(<App/>);
    const hasKittensText = wrapper.queryByText(/Kitt/i);
    expect(hasKittensText).toBeInTheDocument();
  })

  it('verifies entire Kittens is in the Document', () => {
    const testDOM = rtl.render(<App/>);
    const hasEntireKittenString = testDOM.queryByText('All about Kittens');
    expect(hasEntireKittenString).toBeInTheDocument();
  })

})


/*  Autogenerated
it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
*/